// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskAsigment.Models;

namespace TaskAsigment.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210224194322_BaseStructure2")]
    partial class BaseStructure2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TaskAsigment.Models.Proyecto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("pk_proyectos");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("TaskAsigment.Models.State", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("id")
                        .HasName("pk_states");

                    b.ToTable("states");
                });

            modelBuilder.Entity("TaskAsigment.Models.Tarea", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("Proyectoid")
                        .HasColumnType("bigint")
                        .HasColumnName("proyectoid");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("state")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("userId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("pk_tareas");

                    b.HasIndex("Proyectoid")
                        .HasDatabaseName("ix_tareas_proyectoid");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_tareas_user_id");

                    b.ToTable("tareas");
                });

            modelBuilder.Entity("TaskAsigment.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TaskAsigment.Models.Tarea", b =>
                {
                    b.HasOne("TaskAsigment.Models.Proyecto", null)
                        .WithMany("tareas")
                        .HasForeignKey("Proyectoid")
                        .HasConstraintName("fk_tareas_proyectos_proyectoid");

                    b.HasOne("TaskAsigment.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .HasConstraintName("fk_tareas_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TaskAsigment.Models.Proyecto", b =>
                {
                    b.Navigation("tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
